SELECT * FROM TB_DEPARTMENT td;
SELECT * FROM TB_STUDENT ts;
SELECT * FROM TB_PROFESSOR tp;
SELECT * FROM TB_CLASS tc;

--1번
SELECT STUDENT_NO, STUDENT_NAME, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD')
FROM TB_STUDENT ts
WHERE DEPARTMENT_NO=002
ORDER BY ENTRANCE_DATE;

--2번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

--3번
SELECT PROFESSOR_NAME 교수이름, SYSDATE-TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6)) 나이
FROM TB_PROFESSOR;
