SELECT * FROM TB_DEPARTMENT td;
SELECT * FROM TB_STUDENT ts;
SELECT * FROM TB_PROFESSOR tp;
SELECT * FROM TB_CLASS tc;

--1번
SELECT DEPARTMENT_NAME "학과 명", CATEGORY 계열
FROM TB_DEPARTMENT;

--2번
SELECT DEPARTMENT_NAME, '의 정원은', CAPACITY, '명입니다.'
FROM TB_DEPARTMENT;

--3번
SELECT DEPARTMENT_NO, DEPARTMENT_NAME
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME= '국어국문학과';

SELECT STUDENT_NAME
FROM TB_STUDENT ts
WHERE DEPARTMENT_NO = 001
AND (STUDENT_SSN LIKE '_______2______' OR STUDENT_SSN LIKE '_______4______')
AND ABSENCE_YN = 'Y';

--4번
SELECT STUDENT_NAME
FROM TB_STUDENT ts
WHERE STUDENT_NO = 'A513079'
OR STUDENT_NO = 'A513090'
OR STUDENT_NO = 'A513091'
OR STUDENT_NO = 'A513110'
OR STUDENT_NO = 'A513119'
ORDER BY 1 DESC;

--5번
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT td
WHERE CAPACITY BETWEEN 20 AND 30;

--6번
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR tp
WHERE DEPARTMENT_NO IS NULL;

--7번
SELECT STUDENT_NAME
FROM TB_STUDENT ts
WHERE DEPARTMENT_NO IS NULL;

--8번
SELECT CLASS_NO
FROM TB_CLASS tc
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9번
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT td;

--10번
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT ts
WHERE TO_CHAR(ENTRANCE_DATE) LIKE '02%'
AND ABSENCE_YN = 'N'
AND STUDENT_ADDRESS LIKE '%전주%';












