SELECT * FROM TB_DEPARTMENT td;
SELECT * FROM TB_STUDENT ts;
SELECT * FROM TB_PROFESSOR tp;
SELECT * FROM TB_CLASS tc;
SELECT * FROM TB_CALSS_PROFESSOR;
SELECT * FROM TB_GRADE;

--1번
SELECT STUDENT_NO, STUDENT_NAME, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD')
FROM TB_STUDENT ts
WHERE DEPARTMENT_NO=002
ORDER BY ENTRANCE_DATE;

--2번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

--3번
SELECT PROFESSOR_NAME 교수이름, FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE('19'||SUBSTR(PROFESSOR_SSN, 1, 6),'YYYYMMDD')) /12) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY 나이;


--4번
SELECT SUBSTR(PROFESSOR_NAME, 2) 이름
FROM TB_PROFESSOR tp;

--5번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT ts
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM (TO_DATE('19' || SUBSTR(STUDENT_SSN, 1, 6), 'YYYYMMDD'))) >= 20;

--6번
SELECT TO_CHAR(TO_DATE(20201225), 'MM/DD (DY)') FROM DUAL;

--7번
--2099.10.11
--2049.10.11
--1999.10.11
--2049.10.11

--8번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT ts
WHERE STUDENT_NO NOT LIKE 'A%';

--9번
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE STUDENT_NAME = '한아름';

--10번
SELECT DEPARTMENT_NO 학과번호, COUNT(DEPARTMENT_NO)
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--11번
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12번
SELECT SUBSTR(TERM_NO, 1, 4) 년도, ROUND(AVG(POINT),1) "년도 별 평점"
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE STUDENT_NAME = '김고운'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 1;

--13번
SELECT DEPARTMENT_NO 학과코드명, NVL(COUNT(STUDENT_NO), 0) "휴학생 수"
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY 1;

SELECT DEPARTMENT_NO 학과코드명, 
SUM(DECODE(ABSENCE_YN, 'Y', 1, 0)) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--14번
SELECT STUDENT_NAME 동일이름, COUNT(*) "동명인 수"
FROM TB_STUDENT S
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1
ORDER BY 1;

--15번
SELECT NVL(SUBSTR(TERM_NO,1,4), ' ') AS 년도, NVL(SUBSTR(TERM_NO,6,1),' ') AS 학기, ROUND(AVG(POINT),1) AS 평점
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE STUDENT_NAME = '김고운'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2))
ORDER BY SUBSTR(TERM_NO,1,4);


SELECT NVL(SUBSTR(TERM_NO,1,4), ' ') AS 년도, NVL(SUBSTR(TERM_NO,5,2),' ') AS 학기, ROUND(AVG(POINT),1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2))
ORDER BY SUBSTR(TERM_NO,1,4);