SELECT * FROM TB_DEPARTMENT td;
SELECT * FROM TB_STUDENT ts;
SELECT * FROM TB_PROFESSOR tp;
SELECT * FROM TB_CLASS tc;
SELECT * FROM TB_CALSS_PROFESSOR;
SELECT * FROM TB_GRADE tg;

--12번
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE tg  USING (STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE tg.TERM_NO=(SELECT CLASS_NO
								FROM TB_CLASS
								WHERE CLASS_NAME='인간관계론')
AND tg.TERM_NO LIKE '2007%';



SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE tg  USING (STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE tg.TERM_NO LIKE '2007%'
AND tg.CLASS_NO=(SELECT CLASS_NO
								FROM TB_CLASS
								WHERE CLASS_NAME='인간관계론');


SELECT TERM_NO
FROM TB_GRADE
WHERE TERM_NO LIKE '2007%';

--그래이드에서 학기 학번 과목번호
--클래스에서 클래스이름이랑 맞는 과목번호

SELECT CLASS_NO
FROM TB_CLASS
WHERE CLASS_NAME='인간관계론'; --인간관계론 과목번호