-- 테이블 만들기
CREATE TABLE TB_MEMBER(
	MEMBER_NO     NUMBER CONSTRAINT TB_MEMBER_PK PRIMARY KEY,
	MEMBER_ID     VARCHAR2(30) NOT NULL UNIQUE,
	MEMBER_PW     VARCHAR2(30) NOT NULL,
	MEMBER_NAME   VARCHAR2(30) NOT NULL,
	SIGNUP_DATE DATE DEFAULT CURRENT_DATE
);

COMMENT ON COLUMN TB_MEMBER.MEMBER_NO     IS '회원 번호';
COMMENT ON COLUMN TB_MEMBER.MEMBER_ID     IS '회원 아이디';
COMMENT ON COLUMN TB_MEMBER.MEMBER_PW     IS '회원 비밀번호';
COMMENT ON COLUMN TB_MEMBER.MEMBER_NAME   IS '회원 이름';
COMMENT ON COLUMN TB_MEMBER.SIGNUP_DATE IS '회원 가입일';


-- MEMBER_NO 컬럼에 삽입될 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

INSERT INTO TB_MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', 'pass01', '유저일', DEFAULT );

INSERT INTO TB_MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user02', 'pass02', '유저이', DEFAULT );

SELECT * FROM TB_MEMBER
ORDER BY 1;

----------------------------------------------------------------------------

-- 테이블 만들기
CREATE TABLE TB_TODO(
	TODO_NO     NUMBER CONSTRAINT TB_MEMBER_PK PRIMARY KEY,
	MEMBER_ID     VARCHAR2(30) NOT NULL UNIQUE,
	TODO_TITLE     VARCHAR2(30) NOT NULL,
	COMPLETE_YN   CHAR(1) NOT NULL,
	WRITE_DATE DATE DEFAULT CURRENT_DATE
);

COMMENT ON COLUMN TB_TODO.TODO_NO     IS '할 일 번호';
COMMENT ON COLUMN TB_TODO.MEMBER_ID     IS '회원 아이디';
COMMENT ON COLUMN TB_TODO.TODO_TITLE     IS '할 일 제목';
COMMENT ON COLUMN TB_TODO.COMPLETE_YN   IS '완료 여부';
COMMENT ON COLUMN TB_TODO.WRITE_DATE IS '작성일';


-- TODO_NO 컬럼에 삽입될 시퀀스 생성
CREATE SEQUENCE SEQ_USER_NO NOCACHE;
